
int pif = 3;
int i_j9  = (((12-1)+(3*4))*4) * pif - "kaka";
float paf;
string k = "pif";

int g()
{
    k = 12;
}

int f(char c, string pouf)
{
    pif += g(1);
    g(38);
    if (pif + 0)
    {
        c = c + 2;
        k = 12;
        k += 4;
        int paf;
    }
    else if (c == 2)
    {
        g(12);
    }
   while (k < 89)
    {
        k += 1;
    }
}

class A
{
    int f(int k)
    {
        k = "pouf";
    }
}

class B {}

class AB : A, B
{
    int k;
    int pif = 3;
}

A a;
