
class A
{
    int _m;
    flaot _m2;

    bool __init__(A self, int m)
    {
        _m = m.pif +5;
        int pif = 12 + m;
        int hello(A self)
        {

        }
        while (pif > 0)
        {
            pif -= 1;
        }


    }

    string __str__(A self, int m)
    {
        _m = m;
        int pif = 12 + m;
        while (pif < 89)
        {
            pif += 1 + 1 +2;
        }
        return "pif";
    }

}
